on:
  push:

env:
  number: one

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v4.2.2
    - name: show env
      if: false
      run: env | sort
    
