on:
  push:
# #this will not work!
#     branches:
#       - main
#     branches-ignore:
#       - test

env:
  number: one

jobs:
  first_job:
    if: false
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v4.2.2
    - name: show env
      if: false
      run: env | sort
    
  challenge1_job1:
    if: false
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps: 
      - name: Print date
        run: date

  challenge1_job2:
    if: false
    needs: [challenge1_job1]
    runs-on: ubuntu-latest
    steps:
      - name: Finish
        run: echo "Completed"
