name: try composite

on:
  push:

jobs:
  use_action:
    runs-on: ubuntu-latest
    steps: 
      - name: test action
        uses: .github/actions/envoy
        with: 
          message: Oylala

